# Main configuration file, contains global settings/info
---

# Available instruments in the ETC
instruments: [lris, nires, deimos, hires, nirc2, kcwi, esi]

# Default values
defaults:
  instrument: nires
  exposure: [3600 s]  # List of default values, will be overridden by GUI
  signal_noise_ratio: [10]  # List of default values, will be overridden by GUI
  target: signal_noise_ratio
  default_wavelengths_number: 500  # If wavelengths aren't explicitly given, calculate array from min to max w/ default_wavelengths_number of points
  dithers: 1
  reads: 2
  repeats: 0
  coadds: 0
  binning: [1, 1]
  
telescope_area: 75.76 m^2

# Options for number of reads
reads_options: [2, 4, 8, 16, 32, 64, 128]

# Options for ccd binning [spatial, spectral]
binning_options: [ [1,1], [1,2], [2,1], [2,2] ]