# Main configuration file, contains global settings/info
---

# Available instruments in the ETC
instruments: ['deimos', 'test']

# Default values
defaults:
  instrument: 'deimos'
  exposure: 3600 s
  snr: None
  dither: 1
  read: 2
  repeat: 0
  coadd: 0

# Options for dithering
dithers: {min: 1, max: 100}

# Options for number of reads
reads: [2, 4, 8, 16, 32, 64]

# Options for repeats
repeats: {min: 0, max: 50}

# Options for coadds
coadds: {min: 0, max: 50}