# Main configuration file, contains global settings/info
---

# Available instruments in the ETC
instruments: [nires, test]

# Default values
defaults:
  instrument: nires
  exposure: [3600 s]
  signal_noise_ratio: [10, 20]
  target: signal_noise_ratio
  default_wavelengths_number: 500  # If wavelengths aren't explicitly given, calculate array from min to max w/ default_wavelengths_number of points
  dither: 1
  read: 2
  repeat: 0
  coadd: 0
  
telescope_area: 75.76 m^2

# Options for dithering
dithers: {min: 1, max: 100}

# Options for number of reads
reads: [2, 4, 8, 16, 32, 64]

# Options for repeats
repeats: {min: 0, max: 50}

# Options for coadds
coadds: {min: 0, max: 50}