---

# default values
defaults:
  grating: '600ZD'
  filter: 'GG400'
  slit: 10 mm
  binning: '1x1'

# grating options
gratings: ['600ZD', '830G', '900ZD', '1200G', '1200B']  # Imaging mode replaces grating w/ mirror, how does this affect throughput? Should I have grating: 'None' or mode: 'Image'?
# Imaging mode ~ .4 throughput at 6000A...

# filter options
filters: ['GG400', 'GG455', 'OG550']

# binning options
binnings: ['1x1', '1x2', '2x1', '2x2']