---

defaults:
  type: qso
  brightness: 18 AB
  redshift: 0.0  # negative for blueshift

templates:
  point_source: point_source_template.txt
  qso: qso_template.txt
  seyfert1: seyfert1_template.txt
  seyfert2: seyfert2_template.txt
  blackbody: blackbody_template.txt

types: [point_source, qso, seyfert1, seyfert2, blackbody]