---

defaults:
  type: qso
  brightness: 18 AB
  redshift: 0.0  # negative for blueshift

source_types:

  gaussian:
    name: Gaussian
    parameters:
      fwhm: 200 nm
      wavelength: 2 micron

  blackbody:
    name: Blackbody
    parameters:
      temperature: 5000 K

  power:
    name: Power Law
    parameters:
      wavelength: 1 micron
      index: -2

  flat:
    name: Flat

#  vega:
#    name: Vega
#    filename: vega_template.txt

  qso:
    name: QSO
    filename: qso_template.txt

  seyfert1:
    name: Seyfert 1
    filename: seyfert1_template.txt

  seyfert2:
    name: Seyfert 2
    filename: seyfert2_template.txt

# Path (absolute or relative) to directory containing source template files
template_filepath: source/